#!/usr/bin/env bash
# print best school 10 times

for i in {1..100}
do
	if ((i % 3 == 0 && i % 5 == 0))
	then
		printf '%s\n' 'FizzBuzz'
	elif ((i % 3 == 0))
	then
		printf '%s\n' 'Fizz'
	elif ((i % 5 == 0))
	then
		printf '%s\n' 'Buzz'
	else
		printf '%s\n' $i
	fi
done
