#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
i=0
while ((i < 10))
do
	((i++))
	if ((i == 9))
	then
		printf '%s\n' 'Best School'
		printf '%s\n' 'Hi'
	else
		printf '%s\n' 'Best School'
	fi
	
done
