#!/usr/bin/env bash
# print best school 10 times
i=0
while ((i < 20))
do
	((i++))
	case $i in 
		4)
			printf '%s\n' $i
			printf '%s\n' 'bad luck from China'
		;;
		9)
			printf '%s\n' $i
			printf '%s\n' 'bad luck from Japan'
		;;
		17)
			printf '%s\n' $i
			printf '%s\n' 'bad luck from Italy'
		;;
		*)
			printf '%s\n' $i
		;;
	esac
done
