#!/usr/bin/env bash
# print best school 10 times
min=0
hour=0
while ((hour < 12))
do
	((min++))
	if ((min == 60))
	then
		((hour++))
		printf '%s\n' "Hour: $hour"
		min=1
	else
		printf '%s\n' $min
	fi
	
done
