#!/usr/bin/env bash
# print best school 10 times
min=0
hour=0
while ((hour < 13))
do
	((min++))
	if ((min == 60))
	then
		((hour++))
		if ((hour < 13))
		then
			printf '%s\n' "Hour: $hour"
			min=1
		fi
	else
		printf '%s\n' $min
	fi
	
done
