#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
#	* display hours from 0 to 12
#	* display minutes from 1 to 59
hour=0
while ((hour < 13))
do
	min=1
	printf '%s\n' "Hour: $hour"
	while ((min < 60))
	do
		printf '%s\n' $min
		((min++))
	done
	((hour++))
	
	
done
