#!/usr/bin/env bash
# Write a Bash script that displays:
# 	* The content of the current directory
# 	* In a list format
# 	* Where only the part of the name after the first dash is displayed (refer to the example)
i=$(ls)
for x in $i
do
	file=$(echo "$x" | cut -d - -f 2)
	echo "$file" 
done
